excluded:
- Pods
- Snowman/Support/AppDelegate.swift
- Snowman/Source/Component/CalendarView
- Snowman/Source/Feature/Calendar
- Snowman/Source/Feature/History
- Snowman/Resource/Color.swift
- Snowman/Source/Feature/Home/Cell/HomeTodoCell.swift
